version: '2'
services:
    jhipsterfirstprogram-app:
        image: jhipsterfirstprogram
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterfirstprogram-mysql:3306/jhipsterfirstprogram?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterfirstprogram-mysql:
        extends:
            file: mysql.yml
            service: jhipsterfirstprogram-mysql
